name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  github:
    description: 'github event info'
    required: true
  job:
    description: 'job info'
    required: true
  steps:
    description: 'steps info'
    required: true
  github_token:
    description: 'github token'
    required: true
  webhook_url:
    description: 'slack webhook url'
    required: true
  message:
    description: 'notification message'
    required: false
  footer:
    description: 'notification footer'
    required: true
  footer_icon:
    description: 'notification footer icon'
    required: false
  fields_builder:
    description: 'fields builder'
    required: false
  karate_results_file:
    description: 'karate results file path if fields_builder is karate'
    required: false
runs:
  using: 'node12'
  main: 'lib/main.js'
