name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  github:
    description: 'github event info'
    required: true
  job:
    description: 'job info'
    required: true
  steps:
    description: 'steps info'
    required: true
  # webhook_url:
  #   description: 'slack webhook url'
  #   required: true
runs:
  using: 'node12'
  main: 'lib/main.js'
