name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  github:
    description: 'github event info'
    required: true
  job:
    description: 'job info'
    required: true
  steps:
    description: 'steps info'
    required: true
  webhook_url:
    description: 'slack webhook url'
    required: true
  message:
    description: 'notification message'
    required: false
  footer:
    description: 'notification footer',
    required: true
  footer_icon:
    description: 'notification footer icon',
    required: false
  field_generator:
    description: 'fields generator'
    required: false
runs:
  using: 'node12'
  main: 'lib/main.js'
